spring:
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

logging:
  level:
    org.springframework.data.neo4j: INFO
    com.mito.topology.neo4j: INFO