version: '3.8'

services:
  neo4j:
    image: neo4j:5.11.0
    container_name: topology-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "MATCH () RETURN count(*) as count"]
      interval: 10s
      timeout: 10s
      retries: 20

  topology-neo4j-sdn-ms:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: topology-neo4j-sdn-ms
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: