spring:
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:password}

logging:
  level:
    org.springframework.data.neo4j: DEBUG
    com.mito.topology.neo4j: DEBUG